# Site wide configuration

title: A Curious Crossbreed
description: Navigating the wild waters of web app development
logo: # 120x120 px default image used for Twitter summary card
teaser: default-teaser.jpg
locale:
#url: http://localhost:4000

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Jacob Swartzentruber
  email: jsswart@gmail.com
  twitter:
  google:
    ad-client: 
    ad-slot: 
  bio: This is my bio
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
